language: ruby
rvm:
  - 2.3.3
before_install:
  - openssl aes-256-cbc -K $encrypted_18c18cd4d20c_key -iv $encrypted_18c18cd4d20c_iv -in travis-ci.key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
script:
  - bundle install
  - bundle exec jekyll build
after_success:
  - git clone https://github.com/mritd/mritd.me.git
  - cd mritd.me && rm -rf * && cp -r ../_site/* .
  - git config user.name "mritd"
  - git config user.email "mritd1234@gmail.com"
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --force https://$JEKYLL_GITHUB_TOKEN@github.com/mritd/mritd.me.git master
  - ssh root@mritd.me "docker restart mritd_jekyll_1"
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts: mritd.me
